### ISSUE TITLE
Complete set of instructions for MacOS. Please add to README

### ISSUE THREAD

**Issue by sharjeelsayed** [alphapapa/restic-runner#10]
Here are the complete list of instructions I did to fix all issues on MacOS .Please add them to the README

#Install the following applications using Homebrew. Follow linking instructions for each app as it gets installed
`
brew install restic rclone moreutils gnu-getopt coreutils bash 
`
#Add new export Paths to ~/.bash_profile
`
echo 'export PATH="/usr/local/opt/gnu-getopt/bin:/usr/local/opt/coreutils/libexec/gnubin:$PATH"' >> ~/.bash_profile
`
#Change Shell
`
sudo bash -c 'echo /usr/local/bin/bash >> /etc/shells' && chsh -s /usr/local/bin/bash
`

#Replace the shebang in the restic-runner script
`
echo '#!/usr/bin/env bash' | cat - restic-runner > temp && mv temp restic-runner
`

#Set the value of config_dir
`
config_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"/config
`

**Comment by alphapapa** [comment]
Thanks, but there are a few issues:

1.  Some of the things being installed are not necessary or are out-of-scope here.  e.g. `rclone` is not required.  And what are `moreutils` and `coreutils` for?  Are they actually required?  Other MacOS users haven't mentioned them.  The installation instructions should only specify what's required.
2.  The `PATH` modification commands aren't quite right.  You could use a single `export` command.
3.  Changing shell is out-of-scope for this project.
4.  Why is it necessary to change the shebang?  Is `bash` not available at `/bin/bash` on MacOS?

In general, I want to avoid instructions that are too specific, because they too easily become outdated or don't account for exceptions.  e.g. rather than tell a user every command to type to install and configure a newer Bash, it should tell users what minimum version of Bash is required, and the user should refer to the appropriate documentation.

**Comment by sharjeelsayed** [comment]
>>Some of the things being installed are not necessary or are out-of-scope here. e.g. rclone is not required. And what are moreutils and coreutils for? Are they actually required? Other MacOS users haven't mentioned them. The installation instructions should only specify what's required.

I agree with your point on rclone but if you use cloud services, you will need it.I put it as a generic installation instruction for MasOS users just like how I mentioned restic installation via brew
Many of the commands in the script don't work with built in MacOS utilities and need GNU core utils hence the need for installing coreutils. Probably other MacOS users might have already have this installed ,hence they didn't encounter any issues, but it's required to run the script without errors. 
Since your README mentions chronic and moreutils, I put those installation instructions for it.

>>The PATH modification commands aren't quite right. You could use a single export command.

Fixed

>>Changing shell is out-of-scope for this project. The readme isn't a general guide for MacOS. Users should refer to appropriate documentation for more general things like that.

The built in MasOC bash shell is outdated and needs to be updated to the latest version else it doesn't work for the script and throws a lot of errors, hence the need to install the Homebrew shell and change to that shell.

>>Why is it necessary to change the shebang? Is bash not available at /bin/bash on MacOS?

The script needs to call the newly installed shell for the commands to run, else errors are encountered.

**Comment by alphapapa** [comment]
I appreciate your wanting to help Mac users, but the code you have provided is too specific to your own preferences and system.  For example, telling users to modify `~/.bash_profile` is out-of-scope for this project.  This is not a guide for customizing the shell environment on MacOS.

Also, please use code block syntax so I can read it as code more easily.
