### ISSUE TITLE
Adding variable for restic binary

### ISSUE THREAD

**Issue by etique57** [alphapapa/restic-runner#14]
Hello,

To solve some crontab problems, I added the variable restic_bin at the beginning of the script and replaced the calls to restic by $restic_bin.

**Comment by alphapapa** [comment]
Okay, but the correct way to solve that problem is to set `PATH` in the crontab.  See `man 5 crontab`.

**Comment by etique57** [comment]
I actually followed the advice of this answer:
https://stackoverflow.com/a/2388105

I also find it weird that if PATH was the best practice, the distro packager didn't include it in their default configuration.

Not sure what's the best solution is here, but IMHO a wrapper script should allow to specify the path for the binary, for instance I just switched to a beta binary of restic to address my other issue.

(I'm trying to create a pull request to propose my changes but I can't seem to be able to do it :()

**Comment by alphapapa** [comment]
> I also find it weird that if PATH was the best practice, the distro packager didn't include it in their default configuration.

That's not weird.  There are many distros and many packagers.  And Unix is old.  And it's documented in the man page.

> Not sure what's the best solution is here, but IMHO a wrapper script should allow to specify the path for the binary, for instance I just switched to a beta binary of restic to address my other issue.

I would prefer to avoid adding options inside the script itself, because they cause the script to diverge from upstream, making it difficult for users to merge changes.  So:

1.  There might be a good reason to do this, but for the sake of crontabs isn't one, because there's already a canonical Unix solution (e.g. this answer on that page: https://stackoverflow.com/a/2409369).
2.  If there is a good reason, it would be better to store the path in a config file or symlink or something, rather than in the script itself.
