### ISSUE TITLE
Local metadata cache dir parameter in global 

### ISSUE THREAD

**Issue by etique57** [alphapapa/restic-runner#15]
Hello,

Backup of ~250GB of datasets (photos) results in a 30 minutes run, even though nothing changed.

Reading through it, it seems there's a metadata cache feature:
https://github.com/restic/restic/pull/1040

I would like to activate it, is it possible to set it up in the "global parameters" file? if yes, how?

Thanks!

**Comment by alphapapa** [comment]
This script has nothing to do with metadata caching.

**Comment by etique57** [comment]
Indeed, but I would like to specify for instance another path for the local metadata cache, as well as another parameter like --ignore-inode

(see https://forum.restic.net/t/restic-detecting-non-existing-changes-result-in-long-backup-time/1548/2)

Do I need to use the COMMAND passthrough or is there another way to pass options to the binary from the runner?

Thanks!

**Comment by alphapapa** [comment]
There isn't currently a way to pass arbitrary options to commands; the script has to support them.  That would be a nice option to have; it would need some thoughtful design.

You could use the COMMAND passthrough, yes.

**Comment by etique57** [comment]
Ok, I tried to run the backup using the COMMAND passthrough but it fails:

```
root@server /o/a/restic# restic-runner --repo main --set photos -- command backup --ignore-inode
LOG (2019-04-02 19:44:46): REPO:main SET:photos COMMAND:command
Fatal: nothing to backup, please specify target files/dirs
ERROR: passthrough failed.
```
I would assume the --repo & --set would provide sufficient information for the backup to actually happen but it seems not.

As a workaround I simply hardcoded the --ignore-inode flag in the backup command of the script, it's sufficient for my needs.

**Comment by alphapapa** [comment]
You could use the `--debug` flag to try to debug the argument parsing.

**Comment by alphapapa** [comment]
As a followup, note that your `command` doesn't specify any files to be backed up.  This is what gets actually run:

```
restic backup --ignore-inode
```
Of course, that's not a valid `restic` command line, as the `backup` command requires "target files/dirs".

In contrast, the built-in `backup` command runs `restic` like this:

```sh
    restic backup \
           --one-file-system \
           --exclude-caches \
           $(exclude_if_present) \
           --exclude-file "$exclude_file" \
           --tag "$tag" \
           "${include_paths[@]}"
```

Here's what I recommend at this time: Since the config files are actually sourced Bash scripts, you can copy the `backup` function from the script, put it in `~/.config/restic/runner`, and modify it to add whatever options you need.  You might also change the name to distinguish it, e.g. `backup-etique`.  This would allow you to avoid modifying `restic-runner` itself, making upgrades easier.  Of course, you should keep an eye on changes so you can incorporate any necessary modifications to your version of the function, but I don't expect to be changing that function often.  Then, you can run, e.g.
```sh
restic-runner --repo REPO --set SET backup-etique
```
