### ISSUE TITLE
Documentation: why password is stored on same repo folder

### ISSUE THREAD

**Issue by maniqui** [alphapapa/restic-runner#19]
On project's README, the config file sample for a repo has the following lines:

```
export RESTIC_REPOSITORY=/mnt/backup/restic/REPONAME
export RESTIC_PASSWORD_FILE=$RESTIC_REPOSITORY/password_file
```

If I get it right, on your example, the password for a repo is stored in a file right next to the repo itself. I understand that this might be just a matter of preference, but maybe there's also some rationale behind it? 
I'd guess it makes the backup more "portable", in the sense that if you have the backup drive with both the restic repo and the password for such repo, then you have everything you need to access/restore data from repo. On the other hand, it seems to make the backup location less secure, as an attacker getting access to the backup location can gets his hands both on the backup itself and on the password to access the data on backup.

PS: I'm still wrapping my head around restic and restic-runner.

**Comment by alphapapa** [comment]
You can put your password file anywhere you like.  It's just an example.

For local backups, I don't even want it to be encrypted, because I'm more concerned about losing access to the backup than about an attacker stealing the data.  Restic does not permit unencrypted backups, so the closest one can get is storing the password in a plain-text file, and I choose to store it with the repo's files so it doesn't get lost (e.g. if it were on a different drive, and that drive failed, and that's why I needed to restore from my Restic backup, I'd be lost).
