### ISSUE TITLE
Wrong exit status if no error occurred

### ISSUE THREAD

**Issue by zenofile** [alphapapa/restic-runner#21]
If the script runs without errors, it returns an exit status of `1`.

Since the `errors` variable is only initialized in the `error()` function, that is never called when there are no errors encountered, it is undefined and evaluates to '' in the final test before the script exits.
Therefore the test:

https://github.com/alphapapa/restic-runner/blob/e592a4d6d6c8b752d92e17334e528f48d4d5907e/restic-runner#L606

evaluates to `1` and bash uses that value to exit the script.

Initializing `errors` at the start of the script fixes the issue.

Edit: Nevermind, I just saw the PR adressing the issue: https://github.com/alphapapa/restic-runner/pull/20

**Comment by alphapapa** [comment]
Since you've opened this issue, let's discuss this specific problem here.

I looked through the Bash 5 NEWS, but I can't find anything that would explain this issue: https://lists.gnu.org/archive/html/bug-bash/2019-01/msg00063.html  Can you?  I don't see anything about uninitialized variables evaluating differently, or `-gt` behaving differently.

What do you get when you run these commands?

```
bash --version
bash -c '[[ $nope -gt 0 ]] && echo yes'
```

@primeroz FYI.

Thanks.

**Comment by zenofile** [comment]
I can not see anything in the changelog regarding this issue, no.

When trying your commands with bash down to version 3.0 (via container), the output is the same - except the different version string of course.
```
$ bash --version
GNU bash, version 5.0.7(1)-release (x86_64-redhat-linux-gnu)
$ bash -c '[[ $nope -gt 0 ]] && echo yes'
$ echo $?
1
```
In my understanding, this has always been the case: `$nope` is non-existent and definitely not greater than 0 so the exit status of `[[` is 1 which results in the "script" exiting with exactly that value.

**Comment by alphapapa** [comment]
This line in `restic-runner` is the question:
```sh
exit $errors
```
So the issue is, e.g. `exit $undefined_variable`.  Like:
```sh
$ bash --version
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
$ bash -c '[[ $nope -gt 0 ]] && echo yes'
$ echo $?
1
$  bash -c 'echo ERRORS: $errors; exit $errors'
ERRORS:
$ echo $?
0
```
On my system, `exit $undefined` exits `0`, and it always has AFAIK, in all my scripts.  That makes sense, because an undefined variable expands to nothing, so `exit $undefined` expands to `exit`, which exits `0`.

**Comment by zenofile** [comment]
It does make sense, as long as there was no previous process returning 1, which `[[ ... ]]` does in this case. `exit` ignores the variable and just returns the exit code from `[[ ... ]]`.

**Comment by alphapapa** [comment]
Yes, that explains it.  I added that line recently.

It might seem better to initialize `errors` to 0, and it might be, but to be consistent with that would require also initializing all variables, which I don't want to do here, so I changed the test to use an `if`, which avoids passing the status code to `exit`.

Thanks for your help.
