### ISSUE TITLE
./restic-runner: line 91: fusermount: command not found

### ISSUE THREAD

**Issue by sharjeelsayed** [alphapapa/restic-runner#27]
I encounter this error

`./restic-runner: line 91: fusermount: command not found`

while running

`restic-runner --repo REPONAME --set SETNAME verify-randomly`

I am on macOS Catalina 10.15.7 (19H2) with GNU bash, version 5.0.18(1)-release (x86_64-apple-darwin19.5.0)

Fixed this by replacing Line 91 with 

`umount "$mount_point" || error "Unable to unmount repo from: $mount_point"`

**Comment by alphapapa** [comment]
`umount` requires root privileges, so it is the wrong command to use.  `fusermount` is the correct command for a non-root user to use to unmount a FUSE-mounted filesystem.

Macs have issues like these, because it's a proprietary platform, and Apple refuses to maintain compatibility with free standards.  And I'm afraid I'm not interested in adding workarounds for proprietary platforms to this project.  So, feel free to make such modifications as necessary, and feel free to document them so other Mac users may find them.  

But I won't be modifying this project for the sake of Macs.  I hope you will understand my position.  Thanks.

**Comment by sharjeelsayed** [comment]
`umount` does not require root permissions on macOS

**Comment by alphapapa** [comment]
Very well.  However, on Linux (and probably BSDs as well), it is the wrong command, and I will not add Mac-specific code to this project.
